import localFont from 'next/font/local'
import '../styles/globals.css'

export const metadata = {
  title: 'Fanatic Portal',
  // description: 'Generated by Next.js',
}

const suisse = localFont({
  src: [
    { path: '../styles/fonts/SuisseIntl-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../styles/fonts/SuisseIntl-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../styles/fonts/SuisseIntl-Semibold.woff2', weight: '700', style: 'normal' },
  ],
  display: 'swap',
  variable: '--font-suisse',
})
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${suisse.variable} font-sans`}>
      <body>{children}</body>
    </html>
  )
}
