'use server'

import { payload } from '@/lib/payloadClient'
import { User } from '@/payload-types'

export async function createDiscussionPost({
  title,
  content,
  author,
}: {
  title: string
  content: any
  author: User
}) {
  try {
    console.log('Creating discussion post with data:', {
      title,
      content,
      author: author.id,
      status: 'published',
    })

    const result = await payload.create({
      collection: 'discussionPosts',
      data: {
        title,
        content,
        author: author.id,
        status: 'published',
      },
    })

    console.log('Discussion post created successfully:', result.id)

    // Return both the result and the slug for redirection
    return {
      ...result,
      slug: result.slug, // The slug is auto-generated by the formatSlug hook
    }
  } catch (error) {
    console.error('Error creating discussion post:', error)
    console.error('Error details:', {
      message: error instanceof Error ? error.message : 'Unknown error',
      stack: error instanceof Error ? error.stack : undefined,
      data: { title, content, author: author.id },
    })
    throw new Error('Failed to create discussion post')
  }
}
