import '../globals.css'
import AppNavbar from '@/components/ui/AppNavbar'
import Providers from '@/components/Providers'

export const metadata = {
  title: 'Fanatic Portal',
  // description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main>
            <AppNavbar />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
