import '../styles/globals.css'
import Providers from '@/components/Providers'
import localFont from 'next/font/local'
import { AppSidebar } from '@/components/ui/AppSidebar'

// TODO: Add empty state throughout
// TODO: Add loading state throughout (skeletons)
// TODO: Add error state throughout
// TODO: Add pagination
// TODO: Add user profile
// TODO: Add user settings 
// TODO: Add Fanattic tier badge
// TODO: Add notification system
// TODO: Ensure all pages are gated unless signed in

export const metadata = {
  title: 'Fanatic Portal',
  // description: 'Generated by Next.js',
}

const suisse = localFont({
  src: [
    { path: '../styles/fonts/SuisseIntl-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../styles/fonts/SuisseIntl-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../styles/fonts/SuisseIntl-Semibold.woff2', weight: '700', style: 'normal' },
  ],
  display: 'swap',
  variable: '--font-suisse',
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${suisse.variable} font-sans`}>
      <body>
        <Providers>
          <AppSidebar />
          <main className="w-full mx-auto">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
