import '../styles/globals.css'
import Providers from '@/components/Providers'
import localFont from 'next/font/local'
import { AppSidebar } from '@/components/ui/AppSidebar'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/authOptions'
import { redirect } from 'next/navigation'
import { payload } from '@/lib/payloadClient'

// TODO: Add empty state throughout
// TODO: Add loading state throughout (skeletons)
// TODO: Add error state throughout
// TODO: Add pagination
// TODO: Add user profile
// TODO: Add user settings
// TODO: Add Fanattic tier badge
// TODO: Add notification system
// TODO: Ensure all pages are gated unless signed in

export const metadata = {
  title: 'Fanatic Portal',
  // description: 'Generated by Next.js',
}

const suisse = localFont({
  src: [
    { path: '../styles/fonts/SuisseIntl-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../styles/fonts/SuisseIntl-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../styles/fonts/SuisseIntl-Semibold.woff2', weight: '700', style: 'normal' },
  ],
  display: 'swap',
  variable: '--font-suisse',
})

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions)

  if (!session) {
    redirect('/login')
  }

  const currentUser = (
    await payload.find({
      collection: 'users',
      where: {
        email: {
          equals: session?.user.email,
        },
      },
    })
  ).docs[0]

  return (
    <html lang="en" className={`${suisse.variable} font-sans`}>
      <body>
        <Providers user={currentUser}>
          <AppSidebar />
          <main className="mx-auto w-full">{children}</main>
        </Providers>
      </body>
    </html>
  )
}
